set search_path to kaggle_partly_cloudy_change_hashtags;

\copy (select s1 from raw_train order by id asc) to 's1.labels'
\copy (select s2 from raw_train order by id asc) to 's2.labels'
\copy (select s3 from raw_train order by id asc) to 's3.labels'
\copy (select s4 from raw_train order by id asc) to 's4.labels'
\copy (select s5 from raw_train order by id asc) to 's5.labels'
\copy (select w1 from raw_train order by id asc) to 'w1.labels'
\copy (select w2 from raw_train order by id asc) to 'w2.labels'
\copy (select w3 from raw_train order by id asc) to 'w3.labels'
\copy (select w4 from raw_train order by id asc) to 'w4.labels'
\copy (select k1 from raw_train order by id asc) to 'k1.labels'
\copy (select k2 from raw_train order by id asc) to 'k2.labels'
\copy (select k3 from raw_train order by id asc) to 'k3.labels'
\copy (select k4 from raw_train order by id asc) to 'k4.labels'
\copy (select k5 from raw_train order by id asc) to 'k5.labels'
\copy (select k6 from raw_train order by id asc) to 'k6.labels'
\copy (select k7 from raw_train order by id asc) to 'k7.labels'
\copy (select k8 from raw_train order by id asc) to 'k8.labels'
\copy (select k9 from raw_train order by id asc) to 'k9.labels'
\copy (select k10 from raw_train order by id asc) to 'k10.labels'
\copy (select k11 from raw_train order by id asc) to 'k11.labels'
\copy (select k12 from raw_train order by id asc) to 'k12.labels'
\copy (select k13 from raw_train order by id asc) to 'k13.labels'
\copy (select k14 from raw_train order by id asc) to 'k14.labels'
\copy (select k15 from raw_train order by id asc) to 'k15.labels'
